// The three M3 tool implementations.
//
// Architecture:
//   - Load-bearing tool LOGIC lives in plain async methods on
//     `TeraxlystToolset` (do_prompt_for_user_input, do_propose_diff,
//     do_read_workspace_file). Tests exercise these directly.
//   - A second impl block carrying the rmcp `#[tool_router]` macro wraps
//     each do_* method behind a `#[tool]` adapter that takes `Parameters<T>`
//     and returns `Result<CallToolResult, ErrorData>`. The macro generates
//     a `tool_router()` associated function that pattern-matches on tool
//     name and constructs the Args struct from the incoming JSON; storing
//     the result in `Self::tool_router` at construction time means the
//     generated dispatcher references every Args struct + tool function,
//     so clippy stops flagging them as dead code.
//
// Tool surface (logical, also matches the wire surface when the mcp-stdio
// feature drives the handler):
//   1. prompt_for_user_input(prompt_text, field) -> JSON value
//   2. propose_diff(session_id, file_path, new_content) -> {status}
//   3. read_workspace_file(workspace_path, relative_path) -> string
//
// TODO (M4 wiring): four tracker tools are implemented in
// crate::trackers::mcp_wrappers and exposed as Tauri commands. To expose
// them via MCP, extend TeraxlystToolset with a `db: DbHandle` field
// (constructed in `server::spawn_in_process` from the same handle
// installed in Tauri state), then add do_tracker_* methods + #[tool]
// wrappers in this file.

use std::path::{Component, Path, PathBuf};
use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{CallToolResult, Content, ErrorData};
use rmcp::{tool, tool_router};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use super::diff_pipeline::PendingDiffs;
use super::error::McpError;
use super::prompt_pipeline::PendingPrompts;
use super::types::{DiffStatus, PromptField};

// Tool input shapes. JsonSchema is required by the #[tool_router] macro so
// rmcp can publish the input_schema for each tool over the wire.

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub struct PromptForUserInputArgs {
    pub prompt_text: String,
    pub field: PromptField,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub struct ProposeDiffArgs {
    pub session_id: i64,
    pub file_path: String,
    pub new_content: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub struct ReadWorkspaceFileArgs {
    pub workspace_path: String,
    pub relative_path: String,
}

#[derive(Debug, Serialize)]
pub struct ProposeDiffResult {
    pub proposal_id: i64,
    pub status: DiffStatus,
}

// The toolset struct: held by Tauri state so the prompt/diff resolve
// commands can dispatch, and held by the rmcp adapter (when the feature is
// on) for wire-protocol exposure.
//
// `tool_router` is populated by `Self::tool_router()` (generated by the
// `#[tool_router]` macro on the impl block below). Storing it as a field
// keeps the macro-generated dispatcher reachable from the construction
// path, which means clippy sees every Args struct + tool function as
// used.
#[derive(Clone)]
pub struct TeraxlystToolset {
    pub prompts: PendingPrompts,
    pub diffs: PendingDiffs,
    // Populated by `Self::tool_router()` (generated by the
    // `#[tool_router]` macro). Read at startup by
    // `server::spawn_in_process` for the tool-count log line, and by the
    // rmcp stdio handler when the `mcp-stdio` feature is enabled.
    pub tool_router: ToolRouter<TeraxlystToolset>,
}

impl TeraxlystToolset {
    pub fn new(prompts: PendingPrompts, diffs: PendingDiffs) -> Self {
        Self {
            prompts,
            diffs,
            tool_router: Self::tool_router(),
        }
    }

    // -------------------------------------------------------------------
    // Tool implementations (used by both the rmcp adapter and tests).
    // -------------------------------------------------------------------

    pub async fn do_prompt_for_user_input(
        &self,
        prompt_text: String,
        field: PromptField,
    ) -> Result<Value, McpError> {
        let rx = self.prompts.fire(prompt_text, field).await?;
        rx.await.map_err(|_| McpError::PendingClosed)
    }

    pub async fn do_propose_diff(
        &self,
        session_id: i64,
        file_path: String,
        new_content: String,
    ) -> Result<ProposeDiffResult, McpError> {
        let path = PathBuf::from(file_path);
        let (proposal, rx) = self.diffs.fire(session_id, path, new_content).await?;
        let resolution = rx.await.map_err(|_| McpError::PendingClosed)?;
        Ok(ProposeDiffResult {
            proposal_id: proposal.id,
            status: resolution.status,
        })
    }

    pub async fn do_read_workspace_file(
        &self,
        workspace_path: &str,
        relative_path: &str,
    ) -> Result<String, McpError> {
        // Belt-and-suspenders sandbox check:
        //   1. Lexical pre-check rejects obvious `..` and absolute paths.
        //      Produces a clear error even when the file doesn't exist yet.
        //   2. Canonicalize both workspace and target, then verify the
        //      target starts_with the workspace. This catches symlinks
        //      that escape.
        reject_parent_traversal(relative_path)?;

        let workspace = PathBuf::from(workspace_path);
        let workspace_canon = tokio::fs::canonicalize(&workspace).await.map_err(|e| {
            McpError::Invalid(format!(
                "workspace path not accessible: {} ({})",
                workspace.display(),
                e
            ))
        })?;
        let joined = workspace_canon.join(relative_path);

        let target_canon = tokio::fs::canonicalize(&joined).await.map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                McpError::NotFound(format!("{}", joined.display()))
            } else {
                McpError::Io(e)
            }
        })?;

        if !target_canon.starts_with(&workspace_canon) {
            return Err(McpError::PathEscape(target_canon.display().to_string()));
        }

        // Cap the read at 10 MiB to match the existing fs::file convention.
        let bytes = tokio::fs::read(&target_canon).await?;
        if bytes.len() > 10 * 1024 * 1024 {
            return Err(McpError::Invalid(format!(
                "file too large: {} bytes",
                bytes.len()
            )));
        }
        String::from_utf8(bytes).map_err(|_| McpError::Invalid("file is not UTF-8".into()))
    }
}

// rmcp wire adapter. The `#[tool_router]` macro generates
// `TeraxlystToolset::tool_router() -> ToolRouter<TeraxlystToolset>` whose
// dispatcher pattern-matches the incoming tool name and constructs the
// Args struct from the JSON parameters. We store that router in
// `TeraxlystToolset::tool_router` at construction time, which keeps every
// Args struct + tool function reachable from non-test code so clippy
// doesn't flag them as dead.
//
// The methods here are thin adapters: they delegate to the do_* methods
// and convert the result into a CallToolResult / ErrorData pair.
#[tool_router]
impl TeraxlystToolset {
    #[tool(
        name = "prompt_for_user_input",
        description = "Display a form to the user and await their response."
    )]
    pub async fn rmcp_prompt_for_user_input(
        &self,
        Parameters(args): Parameters<PromptForUserInputArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let value = self
            .do_prompt_for_user_input(args.prompt_text, args.field)
            .await
            .map_err(map_mcp_error)?;
        let text = serde_json::to_string(&value).map_err(|e| {
            ErrorData::internal_error(format!("serialize prompt reply: {}", e), None)
        })?;
        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    #[tool(
        name = "propose_diff",
        description = "Propose a unified diff for a file and await approval."
    )]
    pub async fn rmcp_propose_diff(
        &self,
        Parameters(args): Parameters<ProposeDiffArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = self
            .do_propose_diff(args.session_id, args.file_path, args.new_content)
            .await
            .map_err(map_mcp_error)?;
        let text = serde_json::to_string(&result)
            .map_err(|e| ErrorData::internal_error(format!("serialize diff result: {}", e), None))?;
        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    #[tool(
        name = "read_workspace_file",
        description = "Read a file inside a workspace, with path traversal rejected."
    )]
    pub async fn rmcp_read_workspace_file(
        &self,
        Parameters(args): Parameters<ReadWorkspaceFileArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let body = self
            .do_read_workspace_file(&args.workspace_path, &args.relative_path)
            .await
            .map_err(map_mcp_error)?;
        Ok(CallToolResult::success(vec![Content::text(body)]))
    }
}

fn map_mcp_error(e: McpError) -> ErrorData {
    match e {
        McpError::PathEscape(_) | McpError::Invalid(_) => {
            ErrorData::invalid_params(e.to_string(), None)
        }
        McpError::NotFound(_) => ErrorData::resource_not_found(e.to_string(), None),
        _ => ErrorData::internal_error(e.to_string(), None),
    }
}

fn reject_parent_traversal(rel: &str) -> Result<(), McpError> {
    let p: &Path = Path::new(rel);
    for c in p.components() {
        match c {
            Component::ParentDir => {
                return Err(McpError::PathEscape(rel.to_string()));
            }
            Component::Prefix(_) | Component::RootDir => {
                // Absolute paths are not allowed in the "relative" arg.
                return Err(McpError::PathEscape(rel.to_string()));
            }
            _ => {}
        }
    }
    Ok(())
}

// Re-export Arc<TeraxlystToolset> alias so server.rs has a tidy name.
// Reserved for M3.2 wiring (in-process AI session loops grabbing the
// toolset); the renderer reaches the pipelines via the Tauri commands.
#[allow(dead_code)]
pub type SharedToolset = Arc<TeraxlystToolset>;
